### ISSUE TITLE
为什么不对每个 reducer 都有 loading 标记

### ISSUE THREAD

**Issue by warmhug** [dvajs/dva-loading#1]
现在只是针对 namespace 级别，一个 namespace 里有多个异步请求，没法处理？例如：
![image](https://cloud.githubusercontent.com/assets/2011119/18410364/696c3674-7793-11e6-8abf-d0dd2aea4150.png)

**Comment by sorrycc** [comment]
你是说 effects 层级的 loading 标记 ?

**Comment by warmhug** [comment]
也是的

**Comment by sorrycc** [comment]
effects 层我考虑加下，reducer 是同步操作，和 loading 状态无关的。

**Comment by warmhug** [comment]
effects 里一个 generator 里可能有多个请求，但都对应有 action name，也对应 reducer 里的某一个。想想怎么能收集到并把所有异步请求都加上 loading 状态？另外请求是否 complete 的状态最好也有

**Comment by sorrycc** [comment]
目前的方案只能做到 effect 层面，请求级别的手动处理吧。

**Comment by warmhug** [comment]
这样不太彻底吧？没办法吗？

**Comment by sorrycc** [comment]
loading 状态为啥要做这么细，具体场景是啥? 按我理解到 effect 层就够了。

**Comment by warmhug** [comment]
正常是每个异步请求，页面上都该有 loading 提示的，为什么不做完全呢？effect 里如果每个 generator 里都只写一个异步请求、那也没问题、但实际肯定不会这样。或者这个做到 fetch 里？

**Comment by sorrycc** [comment]
fetch 不是必须的，用户可能不用 dva/fetch 发请求。

异步包含在 effect 里，所以做到 effect 层就可以覆盖所有的 loading 提示了。还是从场景出发，举个需要做到请求层的需求吧，说明下为啥在 effect 层不能满足，再看实现的问题。
