### ISSUE TITLE
state.loading.global无法正确指示dynamic route页面加载状态

### ISSUE THREAD

**Issue by DickyT** [dvajs/dva-loading#10]
## 版本

`0.2.0`

## 如何重现

在一个全局component里尝试增加一个prop用来显示dynamic route loading的状态, 表示是否加载中
```js
function mapStateToProps(state) {
  console.log(`[${new Date()}] - state.loading.global = ${state.loading.global}`);
  return {
    globalLoading: state.loading.global,
  };
}

export default connect(mapStateToProps)(Header);
```
完整代码预览[Header.js](https://github.com/DickyT/dva-example-user-dashboard/blob/master/src/components/MainLayout/Header.js)

## 预计表现

目标route所需的js文件开始加载前`state.loading.global`被设置为true
目标route实际mount之后`state.loading.global`才被设置为false

## 实际表现

目标route所需的js文件并未加载完毕的时候`state.loading.global`就已经被设置为false,
反而在js文件加载完成后`state.loading.global`被短时间设置为true, 最终`state.loading.global`保持false

## 具体重现步骤

使用Chrome的Network限速, 限速到GPRS的50kb/s的速度测试出来的
1. 首先加载出主页`http://localhost:8000/`
2. 开启浏览器限速
3. 点击tab上面Users的超链接(此时的时间是`17:48:43`), Chrome的Network界面可见js文件正在加载
4. 大约于`17:49:12`目标页面的js加载成功, Users的页面以及所有component也已经加载成功
5. 得到如下的浏览器console记录

浏览器console
```
[Sun Jan 29 2017 17:48:43 GMT-0400 (AST)] - state.loading.global = false
[Sun Jan 29 2017 17:49:12 GMT-0400 (AST)] - state.loading.global = false
[Sun Jan 29 2017 17:49:12 GMT-0400 (AST)] - state.loading.global = false
[Sun Jan 29 2017 17:49:12 GMT-0400 (AST)] - state.loading.global = true
[Sun Jan 29 2017 17:49:12 GMT-0400 (AST)] - state.loading.global = true
[Sun Jan 29 2017 17:49:13 GMT-0400 (AST)] - state.loading.global = true
[Sun Jan 29 2017 17:49:13 GMT-0400 (AST)] - state.loading.global = false
```

## 范例项目代码

范例项目直接使用`dva-example-user-dashboard`修改

https://github.com/DickyT/dva-example-user-dashboard

**Comment by DickyT** [comment]
@sorrycc 大神求fix！！！

**Comment by paranoidjk** [comment]
@DickyT  你理解错了，`dva-loading` 是对你 `effects` 里面发出的请求做记录，与js文件加载和组件mount并无必然联系；具体可用`redux-devtool`查看历史的action记录

**Comment by DickyT** [comment]
@paranoidjk 明白了，谢谢你的解释，我一直以为`state.loading.global`这个是对于全局请求的一个加载状态，原来只是把所有model的loading做了一个OR的操作
