### ISSUE TITLE
按照配置还是无效 ~

### ISSUE THREAD

**Issue by xoptimal** [dvajs/dva-loading#11]
```
const app = dva({
  history: browserHistory,
  onError(e) {
    console.log("error:" + e.message);
    message.error(e.message);
  },
});
app.use(createLoading());
app.model(require("./models/logins"));
app.router(require('./router'));
app.start('#root');
```

```
export default {
  namespace    : 'logins',
```

```
function mapStateToProps(state) {
  console.log(state);
  return {
    loading: state.loading.models.logins
  };
}
export default connect(mapStateToProps)(LoginLayout = Form.create({})(LoginLayout));
```

>state : Object {routing: Object, logins: Object, @@dva: 0, loading: Object}
models 里面没有model ....

**Comment by ouzhou** [comment]
我的models也是空的 请问是怎么回事？ @xoptimal

**Comment by xoptimal** [comment]
@ouzhou  抱歉, 现在才看见 ~  models 必须是被调用了才行 ~  也就是走了请求 ~

**Comment by ouzhou** [comment]
`models 必须是被调用了才行`是指我在dva里面注册这个models？

**Comment by xoptimal** [comment]
@ouzhou 注册本身就已经走了 ~  我指的是 loading 是绑定了网络请求的.  你的请求了 才有结果 ...

**Comment by ouzhou** [comment]
我这里为什么只有一个state.loading.global，我的state.loading.models里面是空的
里面有什么黑魔法吗

**Comment by sorrycc** [comment]
初始状态下 model 下是空的，只有执行了 effect 才会在对应的 model 里设值。https://github.com/dvajs/dva-loading/blob/097cc9c/src/index.js#L55

**Comment by xoptimal** [comment]
@ouzhou   楼上正解

**Comment by ouzhou** [comment]
已解决，感谢
