### ISSUE TITLE
dva 页面中大于1个的独立请求，loading的状态怎么改变

### ISSUE THREAD

**Issue by zhouzefei** [dvajs/dva-loading#14]
假设我页面有三个独立的异步请求（1、加载列表List；2、获取省市区(选项数据)；3、获取周边门店(选项数据)），加载列表时需要根据loading的状态显示加载图标，那么如果我三次请求这个dva-loading的状态会如何？

又或者我页面有列表list请求，页面上有级联请求，我的dva-loading的状态会如何？

**Comment by sorrycc** [comment]
可以看下源码，loading 是根据 effect 来的，然后 effect 是有计数器的，多个 effect 的触发会等待全部完成后再把 loading 状态重置为 `false`。
