### ISSUE TITLE
loading 针对effects的用法

### ISSUE THREAD

**Issue by forever4313** [dvajs/dva-loading#15]
@sorrycc 
请问 对于loading的使用。

bind state的时候以下写法正确吗？因为没有找到使用effects的时候应该怎么绑定loading，我尝试以下写法，可以实现我的需求，求最佳写法~~~~
function mapStateToProps({loading}) {
      let bindState = {
       //其他bind的内容
        loading: **loading.effects['deliveryOrder/fetch']**
       };
   return {bindState}
}

**Comment by sorrycc** [comment]
`createLoading()` 时传 `effects: true` 了吗?

**Comment by forever4313** [comment]
@sorrycc 设置了，并且运行是对的，不知道我这个写法是不是对的，会不会造成性能之类的影响

**Comment by sorrycc** [comment]
没性能问题的，参考这里，https://github.com/dvajs/dva-loading/blob/097cc9c/test/index-test.js#L39-L69 。
