### ISSUE TITLE
如何避免子组件发起请求，发出loading action

### ISSUE THREAD

**Issue by ldc4** [dvajs/dva-loading#16]
比如一个model: 商品。
商品列表里面有一个操作：收藏。
能不能不让“收藏”这个异步操作，去发出loading action。

还是说：必须得把"收藏"effect 放到另外一个model中？

@sorrycc 大神，求教

**Comment by sorrycc** [comment]
加配置，然后会有 effect 级别的 loading 状态的，通过 effect 和 model 的组合判断排除收藏的 effect 。
