### ISSUE TITLE
loading.models是什么时候会变？

### ISSUE THREAD

**Issue by DrakeXiang** [dvajs/dva-loading#24]
如题，现在我这里只有初始化的时候会变true，后面用不同query参数请求同一个地址就不会变了

**Comment by sorrycc** [comment]
dispatch action 走到 effect 时会触发改变。

**Comment by DrakeXiang** [comment]
@sorrycc 刚才又试了下，是不是effects里面如果没有直接异步，而是调用另一个产生异步的effects，就不会触发改变？

我这里effect A 本身不做异步，只是处理了下传入数据调用 effect B，这样的话我直接dispatch A不会触发loading的改变，但如果我直接dispatch B就可以触发

**Comment by sorrycc** [comment]
理论上也会的，你可以看下实现代码。
