### ISSUE TITLE
请问怎么排除某个model下的某个effect？

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva-loading#5]
请问怎么排除某个model下的某个effect？

全局还是需要的， 不过某个model下的个别 方法不需要触发的时候如何排除呢？

看代码 应该是有这方面的准备。 但是比较菜，请问怎么实现我的需求呢？ 谢谢。

```
models: {},
...
 if (opts.effects) {
            ret.effects = { ...state.effects, [actionType]: true };
}
```

**Comment by sorrycc** [comment]
```js
import createLoading from 'dva-loading';

const app = dva();
app.use(createLoading({ effects: true }));
```

然后就可以拿到 `state.loading.effects` 了。README 稍后我补充下说明，先看用例吧，https://github.com/dvajs/dva-loading/blob/097cc9c/test/index-test.js#L39-L69
