### ISSUE TITLE
dva-loading怎么用呢..配置了没生效

### ISSUE THREAD

**Issue by l745230** [dvajs/dva-loading#6]
![0c470502-9899-45e0-b6c6-b111ca4dba37](https://cloud.githubusercontent.com/assets/15940920/21006400/c01190b6-bd73-11e6-9f5f-d32ea07dc603.png)

model.js中state reducers effects 有关的showloading代码都删了

**Comment by l745230** [comment]
![7ba84c0e-ee3d-4504-aa5f-f4e4228f9324](https://cloud.githubusercontent.com/assets/15940920/21006548/4eb8c758-bd74-11e6-8970-026fe56fe77c.png)
![dba76b67-bf30-4d8d-b6c4-3d767c43a99b](https://cloud.githubusercontent.com/assets/15940920/21006553/521dd924-bd74-11e6-896f-f3093c121afb.png)

**Comment by sorrycc** [comment]
1. 注册插件

```js
app.use(createLoading());
```

2. connect 时使用

```js
function mapStateToProps(state) {
  console.log(state.loading);
};
```

**Comment by ouzhou** [comment]
我能理解是只要是有请求发起 这个loading.global就会变动吗？
还有我发现我的loading.models是一个空对象，请问这是正常的吗？我注册了2个models，我以为会在这个loading.models里面会有这个两个models的loading状态，但是实际上是空对象。

**Comment by sorrycc** [comment]
只有 effect 会触发 loading 的状态修改。
